# Generated by Django 2.0.4 on 2018-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_learn', '0002_entry_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
