# Generated by Django 2.0.4 on 2018-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[(1, 'Farmhouse'), (2, 'Olive Tomato')], max_length=100),
        ),
    ]
