# Generated by Django 2.0.4 on 2018-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0004_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='isActive',
            field=models.NullBooleanField(),
        ),
    ]
