# Generated by Django 2.0.4 on 2018-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0005_buyer_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
