# Generated by Django 2.0.4 on 2018-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0006_buyer_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
