# Generated by Django 2.0.4 on 2018-04-16 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0007_auto_20180416_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
