# Generated by Django 2.0.4 on 2018-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0008_auto_20180416_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[(1, 'Farmhouse'), (2, 'Olive Tomato')], help_text='Something', max_length=100),
        ),
    ]
