# Generated by Django 2.0.4 on 2018-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0009_auto_20180416_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='attachment',
            field=models.FileField(null=True, upload_to='pictures/'),
        ),
    ]
