# Generated by Django 2.0.4 on 2018-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0010_buyer_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='dp',
            field=models.ImageField(null=True, upload_to='dp/'),
        ),
    ]
