# Generated by Django 2.0.4 on 2018-04-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0014_auto_20180416_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(through='model_learn.GroupRelation', to='model_learn.Person'),
        ),
        migrations.AddField(
            model_name='grouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_learn.Group'),
        ),
        migrations.AddField(
            model_name='grouprelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_learn.Person'),
        ),
    ]
