# Generated by Django 2.0.4 on 2018-04-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0015_auto_20180416_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-name']},
        ),
    ]
