# Generated by Django 2.0.4 on 2018-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_learn', '0016_auto_20180420_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouprelation',
            name='person',
        ),
        migrations.AlterField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(to='model_learn.Person'),
        ),
        migrations.DeleteModel(
            name='GroupRelation',
        ),
    ]
